INSERT INTO CURRENCIES (currency_id, iso_code, currency_name, country, is_default, is_enabled)
VALUES (gen_random_uuid(), 'AUD', 'Australian Dollar', 'Australia', false, true),
       (gen_random_uuid(), 'BGN', 'Bulgarian Lev', 'Bulgaria', false, true),
       (gen_random_uuid(), 'BRL', 'Brazilian Real', 'Brazil', false, true),
       (gen_random_uuid(), 'CAD', 'Canadian Dollar', 'Canada', false, true),
       (gen_random_uuid(), 'CHF', 'Swiss Franc', 'Switzerland', false, true),
       (gen_random_uuid(), 'CNY', 'Chinese Yuan', 'China', false, true),
       (gen_random_uuid(), 'CZK', 'Czech Koruna', 'Czech Republic', false, true),
       (gen_random_uuid(), 'DKK', 'Danish Krone', 'Denmark', false, true),
       (gen_random_uuid(), 'EUR', 'Euro', 'Europe', true, true),
       (gen_random_uuid(), 'GBP', 'Pound Sterling', 'United Kingdom', false, true),
       (gen_random_uuid(), 'HKD', 'Hong Kong Dollar', 'Hong Kong', false, true),
       (gen_random_uuid(), 'HUF', 'Hungarian Forint', 'Hungary', false, true),
       (gen_random_uuid(), 'IDR', 'Indonesian Rupiah', 'Indonesia', false, true),
       (gen_random_uuid(), 'ILS', 'Israeli New Sheqel', 'Israel', false, true),
       (gen_random_uuid(), 'INR', 'Indian Rupee', 'India', false, true),
       (gen_random_uuid(), 'ISK', 'Icelandic Krona', 'Iceland', false, true),
       (gen_random_uuid(), 'JPY', 'Japanese Yen', 'Japan', false, true),
       (gen_random_uuid(), 'KRW', 'South Korean Won', 'South Korea', false, true),
       (gen_random_uuid(), 'MXN', 'Mexican Peso', 'Mexico', false, true),
       (gen_random_uuid(), 'MYR', 'Malaysian Ringgit', 'Malaysia', false, true),
       (gen_random_uuid(), 'NOK', 'Norwegian Krone', 'Norway', false, true),
       (gen_random_uuid(), 'NZD', 'New Zealand Dollar', 'New Zealand', false, true),
       (gen_random_uuid(), 'PHP', 'Philippine Peso', 'Philippines', false, true),
       (gen_random_uuid(), 'PLN', 'Polish Zloty', 'Poland', false, true),
       (gen_random_uuid(), 'RON', 'Romanian Leu', 'Romania', false, true),
       (gen_random_uuid(), 'SEK', 'Swedish Krona', 'Sweden', false, true),
       (gen_random_uuid(), 'SGD', 'Singapore Dollar', 'Singapore', false, true),
       (gen_random_uuid(), 'THB', 'Thai Baht', 'Thailand', false, true),
       (gen_random_uuid(), 'TRY', 'Turkish Lira', 'Turkey', false, true),
       (gen_random_uuid(), 'USD', 'United States Dollar', 'United States', false, true),
       (gen_random_uuid(), 'ZAR', 'South African Rand', 'South Africa', false, true);