apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: moneyverse-kafka
  name: moneyverse-kafka
spec:
  serviceName: moneyverse-kafka
  replicas: 1
  selector:
    matchLabels:
      service: moneyverse-kafka
  template:
    metadata:
      labels:
        service: moneyverse-kafka
    spec:
      enableServiceLinks: false
      containers:
        - name: moneyverse-kafka
          imagePullPolicy: IfNotPresent
          image: {{ .Values.confluent.kafka }}:{{ .Values.confluent.version }}
          ports:
            - containerPort: 29092
            - containerPort: 9092
          env:
            - name: CONFLUENT_SUPPORT_CUSTOMER_ID
              value: "anonymous"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://moneyverse-kafka:29092,LISTENER_EXTERNAL://localhost:9092"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://:29092,LISTENER_EXTERNAL://:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT"
            - name: KAFKA_NUM_PARTITIONS
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_LOG_CLEANUP_POLICY
              value: "compact"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "moneyverse-zookeeper:2181"
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: kafka-data
      hostname: moneyverse-kafka
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi