CREATE TABLE account_category_translations
(
    translation_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_category_id BIGINT                                  NOT NULL,
    locale              VARCHAR(10)                             NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    description         VARCHAR(255),
    CONSTRAINT pk_account_category_translations PRIMARY KEY (translation_id)
);

ALTER TABLE account_category_translations
    ADD CONSTRAINT uc_a422d0241d991134134088be1 UNIQUE (account_category_id, locale);

ALTER TABLE account_category_translations
    ADD CONSTRAINT FK_ACCOUNT_CATEGORY_TRANSLATIONS_ON_ACCOUNT_CATEGORY FOREIGN KEY (account_category_id) REFERENCES account_categories (account_category_id);