apiVersion: v2
name: currency-management
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: helm-library
    version: "0.1.0"
    repository: file://../helm-library