export enum TransactionSseEventEnum {
  TRANSACTION_CREATED = 'TRANSACTION_CREATED',
  TRANSACTION_UPDATED = 'TRANSACTION_UPDATED',
  TRANSACTION_DELETED = 'TRANSACTION_DELETED',
}

export enum TransferSseEventEnum {
  TRANSFER_CREATED = 'TRANSFER_CREATED',
  TRANSFER_UPDATED = 'TRANSFER_UPDATED',
  TRANSFER_DELETED = 'TRANSFER_DELETED',
}
