INSERT INTO DEFAULT_CATEGORIES (default_category_id, name, description, background_color, text_color, icon)
VALUES (gen_random_uuid(), 'Income', 'Money received from employment, investments, or other sources.', '#DCFCE7',
        '#22C55E', 'circle-dollar-sign'),
       (gen_random_uuid(), 'Housing',
        'Expenses related to housing such as rent, mortgage payments, maintenance, and property taxes.', '#DBEAFE',
        '#3B82F6', 'house'),
       (gen_random_uuid(), 'Entertainment',
        'Costs for leisure activities including movies, concerts, sports events, and hobbies.', '#F3E8FF', '#A855F7',
        'drama'),
       (gen_random_uuid(), 'Food & Drink',
        'Expenses for groceries, dining out, beverages, and other food-related purchases.', '#FFEDD5', '#F97316',
        'utensils-crossed'),
       (gen_random_uuid(), 'Shopping',
        'Expenditures on retail purchases such as clothing, electronics, and miscellaneous goods.', '#FEF9C3',
        '#EAB308', 'shopping-cart'),
       (gen_random_uuid(), 'Healthcare',
        'Costs for medical services, prescriptions, and other health-related expenses.', '#FEF9C3', '#EAB308', 'pill'),
       (gen_random_uuid(), 'Insurance',
        'Payments for various insurance policies including health, auto, home, and life insurance.', '#FEE2E2',
        '#EF4444', 'piggy-bank'),
       (gen_random_uuid(), 'Utilities',
        'Essential service expenses including electricity, water, gas, internet, and phone bills.', '#FEE2E2',
        '#EF4444', 'lightbulb'),
       (gen_random_uuid(), 'Transportation',
        'Expenses for commuting, fuel, vehicle maintenance, public transit, or ride-sharing services.', '#F3E8FF',
        '#A855F7', 'bus'),
       (gen_random_uuid(), 'Education', 'Costs for tuition, books, supplies, and other education-related expenses.',
        '#FEE2E2', '#EF4444', 'book'),
       (gen_random_uuid(), 'Gifts & Donations', 'Expenditures on gifts and charitable contributions.', '#E0F2FE',
        '#0EA5E9', 'hand-helping'),
       (gen_random_uuid(), 'Subscriptions',
        'Recurring payments for services such as streaming platforms, magazines, or memberships.', '#FEF9C3', '#EAB308',
        'credit-card');