CREATE TABLE default_category_translations
(
    translation_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    default_category_id UUID                                    NOT NULL,
    locale              VARCHAR(10)                             NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    description         VARCHAR(255),
    CONSTRAINT pk_default_category_translations PRIMARY KEY (translation_id)
);

ALTER TABLE default_category_translations
    ADD CONSTRAINT uc_f029424f673190c49cc36c2b0 UNIQUE (default_category_id, locale);

ALTER TABLE default_category_translations
    ADD CONSTRAINT FK_DEFAULT_CATEGORY_TRANSLATIONS_ON_DEFAULT_CATEGORY FOREIGN KEY (default_category_id) REFERENCES default_categories (default_category_id);