INSERT INTO CURRENCIES (iso_code, currency_name, country, is_default, is_enabled)
VALUES ('AUD', 'Australian Dollar', 'Australia', false, true),
       ('BGN', 'Bulgarian Lev', 'Bulgaria', false, true),
       ('BRL', 'Brazilian Real', 'Brazil', false, true),
       ('CAD', 'Canadian Dollar', 'Canada', false, true),
       ('CHF', 'Swiss Franc', 'Switzerland', false, true),
       ('CNY', 'Chinese Yuan', 'China', false, true),
       ('CZK', 'Czech Koruna', 'Czech Republic', false, true),
       ('DKK', 'Danish Krone', 'Denmark', false, true),
       ('EUR', 'Euro', 'Europe', true, true),
       ('GBP', 'Pound Sterling', 'United Kingdom', false, true),
       ('HKD', 'Hong Kong Dollar', 'Hong Kong', false, true),
       ('HUF', 'Hungarian Forint', 'Hungary', false, true),
       ('IDR', 'Indonesian Rupiah', 'Indonesia', false, true),
       ('ILS', 'Israeli New Sheqel', 'Israel', false, true),
       ('INR', 'Indian Rupee', 'India', false, true),
       ('ISK', 'Icelandic Krona', 'Iceland', false, true),
       ('JPY', 'Japanese Yen', 'Japan', false, true),
       ('KRW', 'South Korean Won', 'South Korea', false, true),
       ('MXN', 'Mexican Peso', 'Mexico', false, true),
       ('MYR', 'Malaysian Ringgit', 'Malaysia', false, true),
       ('NOK', 'Norwegian Krone', 'Norway', false, true),
       ('NZD', 'New Zealand Dollar', 'New Zealand', false, true),
       ('PHP', 'Philippine Peso', 'Philippines', false, true),
       ('PLN', 'Polish Zloty', 'Poland', false, true),
       ('RON', 'Romanian Leu', 'Romania', false, true),
       ('SEK', 'Swedish Krona', 'Sweden', false, true),
       ('SGD', 'Singapore Dollar', 'Singapore', false, true),
       ('THB', 'Thai Baht', 'Thailand', false, true),
       ('TRY', 'Turkish Lira', 'Turkey', false, true),
       ('USD', 'United States Dollar', 'United States', true, true),
       ('ZAR', 'South African Rand', 'South Africa', false, true);