INSERT INTO DEFAULT_CATEGORIES (default_category_id, name, description, color, icon)
VALUES (gen_random_uuid(), 'Income', 'Money received from employment, investments, or other sources.', 'green',
        'circle-dollar-sign'),
       (gen_random_uuid(), 'Housing',
        'Expenses related to housing such as rent, mortgage payments, maintenance, and property taxes.', 'blue',
        'house'),
       (gen_random_uuid(), 'Entertainment',
        'Costs for leisure activities including movies, concerts, sports events, and hobbies.', 'purple',
        'drama'),
       (gen_random_uuid(), 'Food & Drink',
        'Expenses for groceries, dining out, beverages, and other food-related purchases.', 'orange',
        'utensils-crossed'),
       (gen_random_uuid(), 'Shopping',
        'Expenditures on retail purchases such as clothing, electronics, and miscellaneous goods.', 'yellow',
        'shopping-cart'),
       (gen_random_uuid(), 'Healthcare',
        'Costs for medical services, prescriptions, and other health-related expenses.', 'yellow', 'pill'),
       (gen_random_uuid(), 'Insurance',
        'Payments for various insurance policies including health, auto, home, and life insurance.', 'red',
        'piggy-bank'),
       (gen_random_uuid(), 'Utilities',
        'Essential service expenses including electricity, water, gas, internet, and phone bills.', 'red', 'lightbulb'),
       (gen_random_uuid(), 'Transportation',
        'Expenses for commuting, fuel, vehicle maintenance, public transit, or ride-sharing services.', 'purple',
        'bus'),
       (gen_random_uuid(), 'Education', 'Costs for tuition, books, supplies, and other education-related expenses.',
        'red', 'book'),
       (gen_random_uuid(), 'Gifts & Donations', 'Expenditures on gifts and charitable contributions.',
        'sky', 'hand-helping'),
       (gen_random_uuid(), 'Subscriptions',
        'Recurring payments for services such as streaming platforms, magazines, or memberships.', 'yellow',
        'credit-card');