CREATE TABLE account_categories
(
    account_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    description         VARCHAR(255),
    CONSTRAINT pk_account_categories PRIMARY KEY (account_category_id)
);

ALTER TABLE account_categories
    ADD CONSTRAINT uc_account_categories_name UNIQUE (name);