CREATE TABLE account_categories
(
    account_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    description         VARCHAR(255),
    CONSTRAINT pk_account_categories PRIMARY KEY (account_category_id)
);

CREATE TABLE accounts
(
    account_id          UUID         NOT NULL,
    username            VARCHAR(64)  NOT NULL,
    account_name        VARCHAR(255) NOT NULL,
    balance             DECIMAL(18, 2)              DEFAULT 0.0,
    balance_target      DECIMAL(18, 2),
    account_description VARCHAR(255),
    is_default          BOOLEAN                     DEFAULT FALSE,
    currency            VARCHAR(3)   NOT NULL,
    account_category    BIGINT       NOT NULL,
    created_by          VARCHAR(255) NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by          VARCHAR(255),
    updated_at          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_accounts PRIMARY KEY (account_id)
);

ALTER TABLE account_categories
    ADD CONSTRAINT uc_account_categories_name UNIQUE (name);

ALTER TABLE accounts
    ADD CONSTRAINT FK_ACCOUNTS_ON_ACCOUNT_CATEGORY FOREIGN KEY (account_category) REFERENCES account_categories (account_category_id) ON DELETE RESTRICT;