import {
  BookIcon,
  BoxIcon,
  BusIcon,
  CheckIcon,
  CircleCheckIcon,
  CircleDollarSignIcon,
  CircleUserRound,
  CircleXIcon, CornerDownRightIcon,
  CreditCardIcon,
  DramaIcon, EllipsisIcon,
  EyeIcon,
  HandHelpingIcon,
  HomeIcon,
  HouseIcon,
  InfoIcon,
  LayersIcon,
  LightbulbIcon,
  LogOutIcon,
  MoonIcon,
  PencilIcon,
  PiggyBankIcon,
  PillIcon,
  PlusIcon,
  SettingsIcon,
  ShapesIcon,
  ShoppingCartIcon,
  StarIcon,
  SunIcon,
  Trash2Icon,
  TriangleAlertIcon,
  UtensilsCrossedIcon,
  WrenchIcon,
  XIcon
} from 'lucide-angular';

export enum IconsEnum {
  CIRCLE_DOLLAR_SIGN = 'circle-dollar-sign',
  BOOK = 'book',
  DRAMA = 'drama',
  UTENSILS_CROSSED = 'utensils-crossed',
  HAND_HELPING = 'hand-helping',
  PILL = 'pill',
  HOUSE = 'house',
  PIGGY_BANK = 'piggy-bank',
  SHOPPING_CART = 'shopping-cart',
  CREDIT_CARD = 'credit-card',
  BUS = 'bus',
  LIGHTBULB = 'lightbulb',
  HOME = 'home',
  LAYERS = 'layers',
  SHAPES = 'shapes',
  SUN = 'sun',
  MOON = 'moon',
  SETTINGS = 'settings',
  LOG_OUT = 'log-out',
  PLUS = 'plus',
  BOX = 'box',
  X = "x",
  CHECK = "check",
  CIRCLE_USER_ROUND = "circle-user-round",
  WRENCH = "wrench",
  STAR = "star",
  EYE = "eye",
  PENCIL = "pencil",
  TRASH = "trash",
  CIRCLE_CHECK = "circle-check",
  CIRCLE_X = "circle-x",
  TRIANGLE_ALERT = "triangle-alert",
  INFO = "info",
  CORNER_DOWN_RIGHT = "corner-down-right",
  ELLIPSIS = "ellipsis"
}

export const ICONS: Record<string, any> = {
  [IconsEnum.CIRCLE_DOLLAR_SIGN]: CircleDollarSignIcon,
  [IconsEnum.BOOK]: BookIcon,
  [IconsEnum.DRAMA]: DramaIcon,
  [IconsEnum.UTENSILS_CROSSED]: UtensilsCrossedIcon,
  [IconsEnum.HAND_HELPING]: HandHelpingIcon,
  [IconsEnum.PILL]: PillIcon,
  [IconsEnum.HOUSE]: HouseIcon,
  [IconsEnum.PIGGY_BANK]: PiggyBankIcon,
  [IconsEnum.SHOPPING_CART]: ShoppingCartIcon,
  [IconsEnum.CREDIT_CARD]: CreditCardIcon,
  [IconsEnum.BUS]: BusIcon,
  [IconsEnum.LIGHTBULB]: LightbulbIcon,
  [IconsEnum.HOME]: HomeIcon,
  [IconsEnum.LAYERS]: LayersIcon,
  [IconsEnum.SHAPES]: ShapesIcon,
  [IconsEnum.SUN]: SunIcon,
  [IconsEnum.MOON]: MoonIcon,
  [IconsEnum.SETTINGS]: SettingsIcon,
  [IconsEnum.LOG_OUT]: LogOutIcon,
  [IconsEnum.PLUS]: PlusIcon,
  [IconsEnum.BOX]: BoxIcon,
  [IconsEnum.X]: XIcon,
  [IconsEnum.CHECK]: CheckIcon,
  [IconsEnum.CIRCLE_USER_ROUND]: CircleUserRound,
  [IconsEnum.WRENCH]: WrenchIcon,
  [IconsEnum.STAR]: StarIcon,
  [IconsEnum.EYE]: EyeIcon,
  [IconsEnum.PENCIL]: PencilIcon,
  [IconsEnum.TRASH]: Trash2Icon,
  [IconsEnum.CIRCLE_CHECK]: CircleCheckIcon,
  [IconsEnum.CIRCLE_X]: CircleXIcon,
  [IconsEnum.TRIANGLE_ALERT]: TriangleAlertIcon,
  [IconsEnum.INFO]: InfoIcon,
  [IconsEnum.CORNER_DOWN_RIGHT]: CornerDownRightIcon,
  [IconsEnum.ELLIPSIS]: EllipsisIcon
};
