import {
  AmbulanceIcon,
  AppleIcon, ArrowLeftRightIcon,
  AwardIcon,
  BabyIcon,
  BanknoteIcon,
  BatteryIcon,
  BedSingleIcon,
  BeerIcon,
  BluetoothIcon,
  BookIcon,
  BoxIcon,
  BriefcaseIcon,
  BusIcon, CalendarSyncIcon,
  CameraIcon,
  CarIcon,
  ChartPieIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleCheckIcon,
  CircleDollarSignIcon, CircleMinusIcon, CirclePlusIcon,
  CircleUserRound,
  CircleXIcon,
  CoinsIcon,
  CookieIcon,
  CookingPotIcon,
  CornerDownRightIcon,
  CpuIcon,
  CreditCardIcon,
  DicesIcon,
  DogIcon,
  DramaIcon,
  DrillIcon,
  DrumIcon,
  DumbbellIcon,
  EllipsisIcon,
  EyeIcon,
  FunnelIcon,
  FunnelXIcon,
  Gamepad2Icon,
  GraduationCapIcon,
  HandHelpingIcon,
  HomeIcon,
  HotelIcon,
  HouseIcon,
  IceCreamConeIcon,
  InfoIcon,
  LayersIcon,
  LightbulbIcon,
  ListFilterIcon,
  ListIcon,
  LogOutIcon,
  MoonIcon,
  NetworkIcon,
  PencilIcon,
  PhoneIcon,
  PiggyBankIcon,
  PillIcon,
  PizzaIcon,
  PlusIcon,
  PrinterIcon,
  PuzzleIcon, RefreshCcwIcon, SearchIcon,
  SettingsIcon,
  ShapesIcon,
  ShieldPlusIcon,
  ShirtIcon,
  ShoppingCartIcon,
  SmartphoneIcon,
  StarIcon,
  SunIcon,
  TableIcon,
  TagIcon,
  TicketIcon,
  Trash2Icon,
  TreesIcon,
  TriangleAlertIcon,
  UtensilsCrossedIcon,
  WrenchIcon,
  XIcon
} from 'lucide-angular';

export enum IconsEnum {
  CIRCLE_DOLLAR_SIGN = 'circle-dollar-sign',
  BOOK = 'book',
  DRAMA = 'drama',
  UTENSILS_CROSSED = 'utensils-crossed',
  HAND_HELPING = 'hand-helping',
  PILL = 'pill',
  HOUSE = 'house',
  PIGGY_BANK = 'piggy-bank',
  SHOPPING_CART = 'shopping-cart',
  CREDIT_CARD = 'credit-card',
  BUS = 'bus',
  LIGHTBULB = 'lightbulb',
  HOME = 'home',
  LAYERS = 'layers',
  SHAPES = 'shapes',
  SUN = 'sun',
  MOON = 'moon',
  SETTINGS = 'settings',
  LOG_OUT = 'log-out',
  PLUS = 'plus',
  BOX = 'box',
  X = "x",
  CHECK = "check",
  CIRCLE_USER_ROUND = "circle-user-round",
  WRENCH = "wrench",
  STAR = "star",
  EYE = "eye",
  PENCIL = "pencil",
  TRASH = "trash",
  CIRCLE_CHECK = "circle-check",
  CIRCLE_X = "circle-x",
  TRIANGLE_ALERT = "triangle-alert",
  INFO = "info",
  CORNER_DOWN_RIGHT = "corner-down-right",
  ELLIPSIS = "ellipsis",
  TABLE = "table",
  TAG = "tag",
  FUNNEL = "funnel",
  FUNNEL_X = "funnel-x",
  CHART_PIE = "chart-pie",
  NETWORK = "network",
  COINS = "coins",
  CHEVRON_DOWN = "chevron-down",
  CHEVRON_UP = "chevron-up",
  LIST_FILTER = "list-filter",
  AMBULANCE = "ambulance",
  APPLE = "apple",
  AWARD = "award",
  BABY = "baby",
  BATTERY = "battery",
  BED_SINGLE = "bed-single",
  BEER = "beer",
  BLUETOOTH = "bluetooth",
  BRIEFCASE = "briefcase",
  HOTEL = "hotel",
  CAMERA = "camera",
  COOKING_POT = "cooking-pot",
  COOKIE = "cookie",
  DICES = "dices",
  DOG = "dog",
  DRILL = "drill",
  DRUM = "drum",
  DUMBBELL = "dumbbell",
  GAMEPAD = "gamepad-2",
  GRADUATION_CAP = "graduation-cap",
  ICE_CREAM_CONE = "ice-cream-cone",
  PHONE = "phone",
  PIZZA = "pizza",
  PRINTER = "printer",
  PUZZLE = "puzzle",
  SHIELD = "shield-plus",
  TICKET = "ticket",
  TREES = "trees",
  CPU = "cpu",
  SMARTPHONE = "smartphone",
  CAR = "car",
  SHIRT = "shirt",
  LIST = "list",
  CIRCLE_PLUS = "circle-plus",
  CIRCLE_MINUS = "circle-minus",
  REFRESH = "refresh-ccw",
  BANKNOTE = "banknote",
  ARROW_LEFT_RIGHT = "arrow-left-right",
  CALENDAR_SYNC = "calendar-sync",
  SEARCH = "search",
  CHEVRON_RIGHT = "chevron-right",
}

export const ICONS: Record<string, any> = {
  [IconsEnum.CIRCLE_DOLLAR_SIGN]: CircleDollarSignIcon,
  [IconsEnum.BOOK]: BookIcon,
  [IconsEnum.DRAMA]: DramaIcon,
  [IconsEnum.UTENSILS_CROSSED]: UtensilsCrossedIcon,
  [IconsEnum.HAND_HELPING]: HandHelpingIcon,
  [IconsEnum.PILL]: PillIcon,
  [IconsEnum.HOUSE]: HouseIcon,
  [IconsEnum.PIGGY_BANK]: PiggyBankIcon,
  [IconsEnum.SHOPPING_CART]: ShoppingCartIcon,
  [IconsEnum.CREDIT_CARD]: CreditCardIcon,
  [IconsEnum.BUS]: BusIcon,
  [IconsEnum.LIGHTBULB]: LightbulbIcon,
  [IconsEnum.HOME]: HomeIcon,
  [IconsEnum.LAYERS]: LayersIcon,
  [IconsEnum.SHAPES]: ShapesIcon,
  [IconsEnum.SUN]: SunIcon,
  [IconsEnum.MOON]: MoonIcon,
  [IconsEnum.SETTINGS]: SettingsIcon,
  [IconsEnum.LOG_OUT]: LogOutIcon,
  [IconsEnum.PLUS]: PlusIcon,
  [IconsEnum.BOX]: BoxIcon,
  [IconsEnum.X]: XIcon,
  [IconsEnum.CHECK]: CheckIcon,
  [IconsEnum.CIRCLE_USER_ROUND]: CircleUserRound,
  [IconsEnum.WRENCH]: WrenchIcon,
  [IconsEnum.STAR]: StarIcon,
  [IconsEnum.EYE]: EyeIcon,
  [IconsEnum.PENCIL]: PencilIcon,
  [IconsEnum.TRASH]: Trash2Icon,
  [IconsEnum.CIRCLE_CHECK]: CircleCheckIcon,
  [IconsEnum.CIRCLE_X]: CircleXIcon,
  [IconsEnum.TRIANGLE_ALERT]: TriangleAlertIcon,
  [IconsEnum.INFO]: InfoIcon,
  [IconsEnum.CORNER_DOWN_RIGHT]: CornerDownRightIcon,
  [IconsEnum.ELLIPSIS]: EllipsisIcon,
  [IconsEnum.TABLE]: TableIcon,
  [IconsEnum.TAG]: TagIcon,
  [IconsEnum.FUNNEL]: FunnelIcon,
  [IconsEnum.FUNNEL_X]: FunnelXIcon,
  [IconsEnum.CHART_PIE]: ChartPieIcon,
  [IconsEnum.NETWORK]: NetworkIcon,
  [IconsEnum.COINS]: CoinsIcon,
  [IconsEnum.CHEVRON_DOWN]: ChevronDownIcon,
  [IconsEnum.CHEVRON_UP]: ChevronUpIcon,
  [IconsEnum.LIST_FILTER]: ListFilterIcon,
  [IconsEnum.AMBULANCE]: AmbulanceIcon,
  [IconsEnum.APPLE]: AppleIcon,
  [IconsEnum.AWARD]: AwardIcon,
  [IconsEnum.BABY]: BabyIcon,
  [IconsEnum.BATTERY]: BatteryIcon,
  [IconsEnum.BED_SINGLE]: BedSingleIcon,
  [IconsEnum.BEER]: BeerIcon,
  [IconsEnum.BLUETOOTH]: BluetoothIcon,
  [IconsEnum.BRIEFCASE]: BriefcaseIcon,
  [IconsEnum.HOTEL]: HotelIcon,
  [IconsEnum.CAMERA]: CameraIcon,
  [IconsEnum.COOKING_POT]: CookingPotIcon,
  [IconsEnum.COOKIE]: CookieIcon,
  [IconsEnum.DICES]: DicesIcon,
  [IconsEnum.DOG]: DogIcon,
  [IconsEnum.DRILL]: DrillIcon,
  [IconsEnum.DRUM]: DrumIcon,
  [IconsEnum.DUMBBELL]: DumbbellIcon,
  [IconsEnum.GAMEPAD]: Gamepad2Icon,
  [IconsEnum.GRADUATION_CAP]: GraduationCapIcon,
  [IconsEnum.ICE_CREAM_CONE]: IceCreamConeIcon,
  [IconsEnum.PHONE]: PhoneIcon,
  [IconsEnum.PIZZA]: PizzaIcon,
  [IconsEnum.PRINTER]: PrinterIcon,
  [IconsEnum.PUZZLE]: PuzzleIcon,
  [IconsEnum.SHIELD]: ShieldPlusIcon,
  [IconsEnum.TICKET]: TicketIcon,
  [IconsEnum.TREES]: TreesIcon,
  [IconsEnum.CPU]: CpuIcon,
  [IconsEnum.SMARTPHONE]: SmartphoneIcon,
  [IconsEnum.CAR]: CarIcon,
  [IconsEnum.SHIRT]: ShirtIcon,
  [IconsEnum.LIST]: ListIcon,
  [IconsEnum.CIRCLE_PLUS]: CirclePlusIcon,
  [IconsEnum.CIRCLE_MINUS]: CircleMinusIcon,
  [IconsEnum.REFRESH]: RefreshCcwIcon,
  [IconsEnum.BANKNOTE]: BanknoteIcon,
  [IconsEnum.ARROW_LEFT_RIGHT]: ArrowLeftRightIcon,
  [IconsEnum.CALENDAR_SYNC]: CalendarSyncIcon,
  [IconsEnum.SEARCH]: SearchIcon,
  [IconsEnum.CHEVRON_RIGHT]: ChevronRightIcon
};
