apiVersion: v2
name: keycloak
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: keycloak
    version: "25.2.0"
    repository: https://charts.bitnami.com/bitnami
  - name: helm-library
    version: "0.1.0"
    repository: file://../helm-library