name: Java CI with Maven

on:
  push:
    branches:
      - "master"
      - "development"
  pull_request:
    branches:
      - "master"
      - "development"

jobs:
  build-test-install:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v4
    
    # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    # Build the project with Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    # Test the project with Maven
    - name: Run Tests with Maven
      run: mvn -B install --file pom.xml
